### ISSUE TITLE
Cyrillic dont work

### ISSUE THREAD

**Issue by markokosticdev** [milosb793/pva#1]
How to use my letter with your project?

**Comment by Myoshu** [comment]
Go to my.ini (you can usually find it in bin/mysql/mysql_version folder) and add this to the end of file

character-set-server=utf8
collation-server=utf8_general_ci

For Lamp -
http://stackoverflow.com/questions/3513773/change-mysql-default-character-set-to-utf-8-in-my-cnf

Make sure to restart mysql service after making the changes.

**Comment by milosb793** [comment]
Huh, i just want to message you Marta. I'm trying almost 1:30h to set it up on Lamp, and still no results... I hate this.

**Comment by milosb793** [comment]
Marta the King: 
http://i.prntscr.com/e53fc676e1a64bf6b24865104212489e.png

**Comment by Myoshu** [comment]
@milosb793  :D we did it!

**Comment by milosb793** [comment]
All that was needed is to edit my.cnf file at location: /etc/mysql and add this code:

```
mysqld]
collation-server = utf8_unicode_ci
init-connect='SET NAMES utf8'
character-set-server = utf8
skip-character-set-client-handshake

[client]
default-character-set   = utf8

[mysql]
default-character-set   = utf8
```

Make sure you execute this file via console, with sudo. 
Example: `sudo nano /etc/mysql/my.cnf`

After that, you need to restart server by command:
`sudo service mysql restart`

That should be all.
